gym:
    n: 3
    num_colors: 2
    game_length: 9 
    seed: null # null is equivalent to python none
    flatten: true
    continuous: null
    # continuous: # overriedes n and game_length when specified since they shift dynamically
    #   start: 2
    #   end: 10
    #   cutoff: .8
    #   logfile: continuous_log.txt
    #   ema_n: 100 # the number of episodes to consider in the EMA
